In [8]:
import numpy as np

#### 연습 문제 1

다음과 같은 행렬을 만든다.

```
10 20 30 40
50 60 70 80
```

In [6]:
matrix1 = np.array([[10, 20, 30, 40], [50, 60, 70, 80]]) 
matrix1

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

#### 연습 문제 2

다음 행렬과 같은 행렬이 있다.

```
m = array([[ 0,  1,  2,  3,  4],
           [ 5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14]])
```

1. 이 행렬에서 값 7 을 인덱싱한다.
2. 이 행렬에서 값 14 을 인덱싱한다.
3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [5]:
m = np.array([[ 0,  1,  2,  3,  4],[ 5,  6,  7,  8,  9],[10, 11, 12, 13, 14]])

matrix1 = m[1,2]
matrix2 = m[-1,-1]
matrix3 = m[1, 1:3]
matrix4 = m[1:3, 2:3]
matrix5 = m[:2, 3:]

#### 연습 문제 1

NumPy를 사용해서 붓꽃 데이터 $x_2$에 대한 벡터 변수 ``x2``를 만든다.

In [10]:
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])
x2

array([[ 4.9],
       [ 3. ],
       [ 1.4],
       [ 0.2]])

#### 연습 문제 2

NumPy를 사용해서 붓꽃 데이터 $X$에 대한 행렬 변수 ``X``를 만든다.

In [16]:
X = np.array([[5.1, 3.5, 1.4, 0.2],[4.9, 3.0, 1.4, 0.2]])
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2]])

#### 연습 문제 3

1. NumPy를 사용해서 붓꽃 데이터 $X$의 전치행렬 $X^T$을 구한다.
2. 전치행렬을 다시 전치한 행렬 $(X^T)^T$을 구한다. 이 행렬과 원래 행렬 $X$을 비교한다.

In [17]:
X.T

array([[ 5.1,  4.9],
       [ 3.5,  3. ],
       [ 1.4,  1.4],
       [ 0.2,  0.2]])

#### 연습 문제 4

1. 영벡터, 일벡터, 정방행렬, 대각행렬, 단위행렬, 대칭행렬의 예를 하나씩 만들어 본다.
2. 위의 벡터와 행렬을 NumPy로 나타내 본다.

In [32]:
vector0 = np.array([[0],[0],[0],[0]])
vector1 = np.array([[1],[1],[1],[1]])
square_matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
diagnal_matrix = np.diag([7, 8, 9])
identity_matrix = np.eye(5)
symmetric_matrix = np.array([[1,2,2,2],[2,1,2,2],[2,2,1,2],[2,2,2,1]])

symmetric_matrix

array([[1, 2, 2, 2],
       [2, 1, 2, 2],
       [2, 2, 1, 2],
       [2, 2, 2, 1]])

#### 연습 문제 1

1. $A$와 $B$가 위와 같을 때 $AB$를 연습장에 손으로 계산하고 NumPy의 계산결과와 맞는지 확인한다.

2. 순서를 바꾸어 $BA$를 연습장에 손으로 계산하고 NumPy로도 계산한다.

3. $A$,, $B$가 다음과 같을 때, $AB$, $BA$를 (계산이 가능하다면) 손 계산과 NumPy 코드로 구한다. $AB$, $BA$ 모두 계산 가능한가?
$$ A = \begin{bmatrix} 1 & 2 & 3 \end{bmatrix} $$
$$ B = \begin{bmatrix} 4 & 7 \\ 5 & 8 \\ 6 & 9 \end{bmatrix} $$

4. $A$,, $B$가 다음과 같을 때, $AB$, $BA$를 (계산이 가능하다면) 손 계산과 NumPy 코드로 구한다. $AB$, $BA$ 모두 계산 가능한가?
$$ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $$
$$ B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} $$

5. $x$가 다음과 같을 때, $x^Tx$와 $xx^T$를 각각 손 계산과 NumPy 코드로 구한다.
$$ x = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix} $$

In [11]:
A = np.array([[1,2,3]]) ## 1*3 행렬
B = np.array([[4,7],[5,8],[6,9]]) ## 2*3 행렬



np.dot(A,B) ## 가능
np.dot(B,A) ## 불가능


ValueError: shapes (3,2) and (1,3) not aligned: 2 (dim 1) != 1 (dim 0)

In [45]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

np.dot(A,B)
np.dot(B,A)

array([[23, 34],
       [31, 46]])

In [50]:
x = np.array([[1],[2],[3]])
np.dot(x.T,x)
np.dot(x,x.T)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

#### 연습 문제 2

다음 행렬의 곱셈을 순서를 바꾸어 두 가지 방법으로 해본다.

$$ \begin{bmatrix} 1 & 2 \end{bmatrix} \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \begin{bmatrix} 5 \\ 6 \end{bmatrix}$$

In [70]:
A = np.array([1,2])
B = np.array([[1,2],[3,4]])
C = np.array([[5],[6]])


np.dot(A,(np.dot(B,C)))
np.dot(np.dot(A,B).T,C)

array([95])

DAY 1 연습 문제 1

예측 문제로 풀 수 있는 데이터 분석의 예를 3가지 생각해 보자.

1. 과거 10년의 출산율과 결혼성년수, 나이에 따른 인구수 데이터 분석으로 현재 신생아수 출력
2. 과자내용을 보고 종류와 이름 알아맞추기
3. 자녀수에 따른 가족 구성원 행복지수 

연습 문제 2

위에서 생각한 3가지 예측 문제의 입력과 출력을 보다 정확하게 정의해 보자. 중요한 점은 다음과 같다.

"~등", "같은 것"이란 용어를 사용하지 않고 정확히 입출력 데이터의 갯수를 정해야 한다.
입력이나 출력 데이터 값의 숫자 예를 제시하면 더욱 좋다. 예를 들어 부동산 가격을 예측하기 위해 면적을 입력 데이터로 사용하기로 했다면 40 제곱미터 혹은 80 제곱미터 등 실제로 어떤 숫자를 입력데이터로 사용할지도 예를 들어 준다.

1. 입력데이터: 과거 10년동안 서울 청년 20세~30세 결혼성년수
2. 입력데이터: 과자의 모양, 색깔, 성분으로 과자 이름 알아맞추기 
3. 입력데이터: 자녀표정에 따른 가족간 만족도 수치

연습 문제 3

위에서 생각한 3가지 예측 문제에 대해 규칙기반의 해결 방법을 생각해보자. 정확한 답이 아니어도 괜찮다.

1. 회귀분석 
2. 분류
3. 분류 후 회귀분석

연습 문제 4

위의 3가지 예측 문제에 대해 학습용 데이터 집합을 만들어본다. 학습용 데이터 집합의 크기는 최소한 각 문제에 대해 10개 이상 만들어보자.

1번 학습용데이터 집합: 


2번 학습용데이터 집합 :
학습용 데이터 1: (입력데이터= 롯데과자 샘플1, 출력데이터=" 샘플1 브랜드 네임 ")
학습용 데이터 2: (입력데이터= 롯데과자 샘플2, 출력데이터="샘플2 브랜드 네임")
학습용 데이터 3: (입력데이터=롯데 과자 샘플3, 출력데이터="샘플3 브랜드 네임")
학습용 데이터 4: (입력데이터=해태제과 샘플1, 출력데이터="해태제과 샘플1 브랜드네임")
학습용 데이터 5: (입력데이터=해태제과 샘플2, 출력데이터="해태제과 샘플2 브랜드네임")
학습용 데이터 6: (입력데이터=해태제과 샘플3, 출력데이터="해태제과 샘플3 브랜드네임")
학습용 데이터 7: (입력데이터=오뚜기제과 샘플1, 출력데이터="오뚜기 제과 샘플1 브랜드네임")
학습용 데이터 8: (입력데이터=오뚜기제과 샘플2, 출력데이터="오뚜기 제과 샘플2 브랜드네임")
학습용 데이터 9: (입력데이터=오뚜기제과 샘플3, 출력데이터="오뚜기 제과 샘플3 브랜드네임")
학습용 데이터 10: (입력데이터=외국브랜드제과 샘플1, 출력데이터="외국브랜드 제과 샘플1")

3번 학습용데이터 집합:
학습용 데이터 1: (입력데이터= 가족 구성원 부모1표정, 출력데이터=" 근엄함 ") 
학습용 데이터 2: (입력데이터= 가족 구성원 사진속 아이1표정, 출력데이터="즐거움")
학습용 데이터 3: (입력데이터=가족 구성원 사진속 아이2표정, 출력데이터="행복함")
학습용 데이터 4: (입력데이터=가족 구성원 사진속 아이3표정, 출력데이터="사랑함")
학습용 데이터 5: (입력데이터=가족 구성원 사진속 아이4표정, 출력데이터="짜증남")
학습용 데이터 6: (입력데이터=가족 구성원 사진속 아이5표정, 출력데이터="질투남")
학습용 데이터 7: (입력데이터=가족 구성원 사진속 아이6표정, 출력데이터="슬픔")
학습용 데이터 8: (입력데이터=가족 구성원 사진속 아이7표정, 출력데이터="동경")
학습용 데이터 9: (입력데이터=가족 구성원 사진속 아이8표정, 출력데이터="존경")
학습용 데이터 10: (입력데이터=가족 구성원 사진속 아이9표정, 출력데이터="화남")

연습 문제 5

지금까지 생각한 예측 문제의 입력 데이터 중 전처리 혹은 인코딩이 필요한 것이 어떤 것인지 확인하고 어떻게 숫자로 바꿀 수 있을지 그 방법을 생각해 보자.

In [ ]:
과자 내용 분류: 전처리- 이미지 전처리 필요, 포토샵을 이용하여 1픽셀당 이미지 숫자변환값을 행렬로 구현
감정 내용 분류: 객관식이 아닌 주관식으로 써져있는 감정내용을 Word2Vec으로 구현하여 감정을 벡터로 구현후 행렬로 집합 
감정 내용 분류: 가족 구성원 사진 분석- 포토샵을 이용하여 사람 표정에 관하여 이미지 숫자 변환값을 행렬로 구현 필요 

연습 문제 6

지금까지 고려했던 예측 문제의 입력 데이터와 출력 데이터가 각각 숫자값인지 카테고리값인지 쓰고 문제가 회귀분석 문제인지 분류 문제인지 결정하라.

In [ ]:
1. 숫자값 ,회귀분석
2. 카테고리값, 분류
3. 숫자값, 회귀분석

## Greek Alphabet 외우기

Α α alpha 알파 
Β β beta 베타 
Γ γ gamma 감마 
Δ δ delta 델타 
Ε ε epsilon 엡실론 
Ζ ζ zeta 지타 
Η η eta 이타 
Θ θ theta 씨타 
Ι ι iota 요타 
Κ κ kappa 카파 
Λ λ lambda 람다 
Μ μ mu 뮤우 
Ν ν nu 뉴우 
Ξ ξ xi 크사이 
Ο ο omicron 오미크론 
Π π pi 파이 
Ρ ρ rho 로오 
Σ σ sigma 씨그마 
Τ τ tau 타우 
Υ υ upsilon 입실론
Φ φ phi 화이 
Χ χ chi 카이 
Ψ ψ psi 프사이 
Ω ω omega 오메가